wily/commands/build.py
When the the default path of "." is reported, this message is ambiguous:
```
Found 20 revisions from 'git' archiver in ..
```
At first glance, this looks like the parent directory, "`..`", rather than the current directory, "`.`", followed by a stop.
=> Quote path in output

HISTORY.md, test/integration/test_graph.py, test/integration/test_report.py, wily/__main__.py, wily/cache.py, wily/commands/graph.py
* Support for configuring the x-axis on the graph command (defaults to history) to a custom metric
* Support for configuring the z-axis (size of bubble on scatter) in graph command by specifying a second metric
* Set metrics to cap at 2 possible options in graph command
* Running the test suite no longer opens 12 browser windows :-)
=> Extend the graph command to support multiple axis and recursive path graphing

HISTORY.md, test/conftest.py, test/integration/test_build.py, test/unit/test_archivers.py, wily/__main__.py, wily/archivers/__init__.py, wily/archivers/filesystem.py, wily/archivers/git.py, wily/cache.py, wily/commands/build.py, wily/state.py
filesystem archiver is the most-basic archiver, if the git archiver is unavailable (i.e. the target path is not a git repository) the build command should fall back to the filesystem archiver.
The expected behaviours are:
Outstanding question:
- If the user runs `wily build -a filesystem` and changes the files, then runs it again - what should happen? For git, it would fail with a "Dirty repository error" to avoid losing unrevisioned changes. For filesystem, I think it should use the last changed date of the files?
=> Add Filesystem archiver

wily/commands/list_metrics.py, wily/operators/__init__.py
The `ALL_OPERATORS` constant is a set in 1.6.0. 
Every lookup to resolve an operator from a string to an operator type results in iteration over the set.
It makes more sense to have ALL_OPERATORS as a dictionary with the name as the key so that lookups are O(1) instead of O(n)
=> change operators set to a dictionary to speed up the lookup functions

HISTORY.md, wily/__init__.py, wily/commands/build.py
Uses `multiprocessing` to create a process pool for each of the operators, once a revision has been checked out using the archiver, the operator harvesters are run in parallel.
In testing this leads to around a 60% reduction in time to build using the default operators (3).
=> Multithreaded builds

HISTORY.md, test/integration/test_build.py, test/integration/test_report.py, wily/archivers/git.py, wily/commands/build.py, wily/operators/__init__.py, wily/operators/cyclomatic.py, wily/operators/halstead.py, wily/operators/maintainability.py, wily/operators/raw.py
Once the build has completed, each revision should store the metrics at a directory level:
- Feature is enabled by default
- If user does `wily report <path>` and the path is a directory, it should show those metrics
- `wily graph` should continue to do recursive file searches for now, perhaps later that can be a feature toggle
- Metric should explicitly state how the aggregate value is calculated. Some, e.g. MI are median, volume, vocab, h1, h2 would all be `sum()` and rankings would be `median`.
=> Aggregate directories

HISTORY.md, wily/__init__.py, wily/config.py, wily/operators/halstead.py
Enable halstead metrics by default and prep 1.10.0 release
=> update release notes and enable halstead by default

wily/operators/halstead.py
Similar to the fix for cyclomatic complexity here:
7ba461c8f7f977a9fae1d3a52a35c8c139cff161
the radon halstead harvester can return errors as a piece of data and we
need to log it rather than attempt to add it to our report.
=> Fix halstead harvester for errors thrown by radon

test/integration/test_all_operators.py, test/unit/test_cyclomatic.py, wily/commands/build.py, wily/commands/diff.py, wily/operators/__init__.py, wily/operators/cyclomatic.py, wily/operators/halstead.py, wily/operators/maintainability.py, wily/operators/raw.py
This is a PR to fix issue #73.
The PR introduces an extra level in the results dict for detailed and total metrics. This is to avoid mangling file metric aggregates and object metrics when the analyzed file happens to include objects that have the same name as the metrics (e.g. a function called `h1`).
=> Bugfix: handle objects that have the same name as the metrics

HISTORY.md, test/conftest.py, test/integration/test_all_operators.py, test/integration/test_complex_commits.py, test/integration/test_diff.py, test/integration/test_report.py, test/integration/test_state.py, test/unit/test_archivers.py, test/unit/test_build_unit.py, test/unit/test_cache.py, test/unit/test_cyclomatic.py, wily/__init__.py, wily/__main__.py, wily/archivers/__init__.py, wily/archivers/filesystem.py, wily/archivers/git.py, wily/cache.py, wily/commands/build.py, wily/commands/diff.py, wily/commands/index.py, wily/commands/report.py, wily/operators/cyclomatic.py, wily/operators/halstead.py, wily/operators/maintainability.py, wily/operators/raw.py, wily/state.py
This change uses the commit metadata in git to see which files have changed then instructs radon to only inspect those changes (instead of scanning all targets).
Had to introduce a "seed" scan that would inspect all files for the first scan, then for subsequent scans, copy values if the file was unchanged.
This means that each indexed revision still has metrics for all files, it's not a delta.
Secondly, the aggregate functions had to be fully tested.
=> Optimize the build process by using git metadata

src/wily/operators/maintainability.py
Maintainability Index scale from 0 to 100 where the lower the value, the worst the Maintainability Index. The current code is set to use colors where lower is better. This patch fixes the index definition to use the correct color code, where higher values are good.
Signed-off-by: Willian Rampazzo <willianr@redhat.com>
=> Fix Maintainability Index aim.

docs/source/commands/rank.rst, docs/source/conf.py, src/wily/__init__.py, src/wily/__main__.py, src/wily/commands/build.py, src/wily/commands/rank.py, test/integration/test_rank.py
Resolves: #104 
Adds support for a `--threshold` function for the `rank` command. If the total value of the used metric is below the threshold, a non-zero exit code is returned (in this case `exit_code == 1`).
@tonybaloney What do you think about the implementation? You already stated that you like the idea of a threshold option for the rank command in the issue-related discussion.
=> Rank threshold option

src/wily/__init__.py, src/wily/config.py, test/integration/test_build.py, test/unit/test_config.py
Hi :wave:
thanks for creating and maintaining great library! 
This PR fixes `wily.cfg` `operators` option parsing to list.
=> fix operators config option parsing

src/wily/config.py, test/unit/test_config.py
=> add cache_path option to wily.cfg

pyproject.toml
`nbformat==4.4.0` is incompatible with Python 3.9 because it relies on the now-removed `encodestring` function in `base64`.
I bumped `nbformat` to 5.1.3, added Python 3.9 as a tox test environment, and ran the tests for 3.6, 3.7, 3.8, and 3.9. All passed for me.
=> Bump nbformat to 5.1.3

src/wily/commands/report.py
=> Sort the metrics in report

src/wily/__main__.py, src/wily/commands/graph.py, test/integration/test_graph.py
This pull request implements aggregated graph support for directories.
It also patches a bug in title creation.
=> Adds support for aggregated graphs + patch title

docs/source/ci.rst
It took me a little bit of work to understand how to run Wily correctly on each pull request on GitHub workflows, so I thought it would be useful to document this for future users
=> docs: Adds a description on how to use Wily on a Github action

src/wily/archivers/__init__.py, src/wily/archivers/filesystem.py, src/wily/archivers/git.py, src/wily/commands/build.py, src/wily/state.py, test/unit/test_archivers.py, test/unit/test_build_unit.py, test/unit/test_cache.py
I discovered that the aggregated statistics were not properly computed.
In particular in case of file movements, file deletions and deeply nested directories.
This PR should resolve the issue. Please validate if this does not break other functionality (as I am relatively new to the code base.)
=> Patch aggregate statistics

docs/source/conf.py, src/wily/__main__.py, src/wily/archivers/__init__.py, src/wily/cache.py, src/wily/commands/diff.py, src/wily/config.py, src/wily/lang.py, src/wily/operators/__init__.py, src/wily/state.py, test/integration/test_build.py, test/integration/test_graph.py, test/unit/test_archivers.py, test/unit/test_build_unit.py, test/unit/test_cli.py, test/unit/test_cyclomatic.py
https://pypi.org/project/pyupgrade
https://pypi.org/project/flynt
https://pypi.org/project/mock vs. https://docs.python.org/3/library/unittest.mock.html
=> pyupgrade --py37-plus

pyproject.toml
#153 makes https://pypi.org/project/mock unnecessary.
> mock is now part of the Python standard library, available as unittest.mock in Python 3.3 onwards.
=> pyproject.toml: Remove dependency `mock`

src/wily/commands/graph.py
Add the ability to graph files that are no longer present in the directory.
Relies on #139
=> Graph deleted files

Makefile, pyproject.toml, setup.cfg, src/wily/archivers/git.py, src/wily/cache.py, src/wily/commands/report.py, src/wily/lang.py, src/wily/operators/maintainability.py, test/conftest.py, test/integration/test_archiver.py, test/integration/test_diff.py, test/integration/test_graph.py, test/integration/test_rank.py, test/integration/test_state.py, test/integration/test_wily.py, test/unit/test_archivers.py, test/unit/test_cache.py
There is one action to do when this commit will be squashed to the main branch:
=> refactor: apply black on wily codebase

.github/workflows/ci.yml, pyproject.toml
I could not use Wily in my project that uses a 5.x version of Plotly because dependencies could not be resolved. This updates the Plotly dependency to be compatible with 5.x. Tests are passing and I have tested it on my project successfully with 5.10.0 so my guess is this is safe. Here's the relevant section of the release notes:
https://community.plotly.com/t/introducing-plotly-py-5-0-0-a-new-federated-jupyter-extension-icicle-charts-and-bar-chart-patterns/54039#warning-backwards-incompatible-changes-2
> Our commitment to semantic versioning requires us to make this release a major version bump (up from 4.14.3) because we are upgrading to version 2.1 of the underlying Plotly.js library, which makes some backwards-incompatible changes to older and deprecated features (see below), but we …
=> Upgrade plotly from 4.x to 5.x

pyproject.toml
Radon 5.x has a smaller dependency set and a few bugfixes, see https://github.com/rubik/radon/blob/master/CHANGELOG.
=> Update radon dependency from 4.x to 5.x

src/wily/__main__.py, src/wily/cache.py, src/wily/commands/build.py, src/wily/commands/graph.py, src/wily/commands/rank.py, src/wily/commands/report.py, src/wily/state.py, test/conftest.py, test/unit/test_archivers.py
https://beta.ruff.rs
% `ruff --select=E712,F401,F541 --statistics .`
```
1	E712	[*] Comparison to `True` should be `cond is True`
4	F401	[*] `pathlib` imported but unused
4	F541	[*] f-string without any placeholders
```
% `ruff --select=E712,F401,F541 --fix .`
```
Found 9 errors (9 fixed, 0 remaining).
```
=> ruff --select=E712,F401,F541 --fix .

.github/workflows/ci.yml
At this point, `3.12-dev` is also a possibility.
=> GitHub Actions: Upgrade to Python 3.11 production release

src/wily/operators/__init__.py
Use a tuple instead of a set to build `ALL_OPERATORS`, keeping list-metrics output stable. As discussed on #179.
=> Make list-metrics output stable (fix #179)

docs/source/conf.py, src/wily/__main__.py, src/wily/commands/build.py, src/wily/commands/diff.py, src/wily/commands/graph.py, src/wily/commands/rank.py, src/wily/config.py, src/wily/state.py, test/conftest.py, test/integration/test_build.py, test/unit/test_archivers.py, test/unit/test_build_unit.py, test/unit/test_cache.py
* This is a proper subset of #174
It only contains the changes to Python files and not the changes to configuration files.  It will prove whether all tests will pass under the current configuration.  When this PR lands, it will make #174 easier to review.
=> ruff recommended code changes from #174

src/wily/commands/report.py
To fix #182, use `errors="xmlcharrefreplace"` in `Path.open()` so we avoid the error and the generated HTML works.
=> Use xmlcharrefreplace to handle codec errors in html report writing (fix #182)

src/wily/commands/report.py
Also replace ESCAPE character when replacing ANSI colors with spans, so they don't get output in the generated HTML. 
Fixes #184.
=> HTML report: replace ESCAPE character (fix #184)

src/wily/__main__.py, src/wily/commands/report.py, test/integration/test_report.py
This add a CLI option and the path to omit lines where delta equals zero or file was not found. I've added a test, but it only checks that the CLI option works. 
Fixes #187.
=> Allow report to only display revisions that have changes (fix #187)

pyproject.toml
Raise ruff's max-args, max-branches and max-statements because CI checks are failing (e.g. in #191) due to ruff finding the following errors:
```
src\wily\__main__.py:263:5: PLR0913 Too many arguments to function call (9 > 8)
|
261 | )
262 | @click.pass_context
263 | def report(
264 |     ctx, file, metrics, number, message, format, console_format, output, changes
265 | ):
|
src\wily\commands\report.py:24:5: PLR0913 Too many arguments to function call (9 > 8)
|
24 | def report(
|     ^^^^^^ PLR0913
25 |     config,
26 |     path,
|
src\wily\commands\report.py:24:5: PLR0912 Too many branches (32 > 31)
|
24 | def report(
|     ^^^^^^ PLR0912
25 |     config,
26 |     path,
|
src\wily\commands\report.py:24:5: PLR0915 Too many statements (94 > 91)
|
24 | def report(
|     ^^^^^^ PLR0915
25 | …
```
=> Fix ruff CI checks

src/wily/commands/rank.py
Only calculate mean rank and print results when some data is found by `rank()`, otherwise print nothing.
This could also be done in a way that prints an empty table with a total of 0, I'm open to doing it that way if it's preferable.
=> Avoid statistics.StatisticsError if rank finds no data (fix #196)

src/wily/__main__.py, src/wily/commands/diff.py, src/wily/commands/index.py, src/wily/commands/list_metrics.py, src/wily/commands/rank.py, src/wily/helper/__init__.py, test/unit/test_helper.py
When piping wily's output (and in other related scenarios) in Windows, users get a `UnicodeEncodeError: 'charmap' codec can't encode characters...` error. This happens because the `DEFAULT_GRID_STYLE` is `"fancy_grid"`, which uses characters outside of what charmap can understand.
This PR introduces checks for `sys.stdout.encoding` and, if it's not UTF-8, makes wily pass `"grid"` instead of `"fancy_grid"` to tabulate as `tablefmt`. It gives comparable output with ASCII-only characters.
Output should be testable once #199 lands.
Fixes #65.
=> Avoid using unicode characters if `sys.stdout` doesn't support them (fix #65)

src/wily/__main__.py, src/wily/cache.py, src/wily/commands/build.py, src/wily/commands/graph.py, src/wily/commands/rank.py, src/wily/commands/report.py, src/wily/locales/en/LC_MESSAGES/messages.po, src/wily/locales/en_AU/LC_MESSAGES/messages.po, src/wily/operators/__init__.py, src/wily/operators/maintainability.py, src/wily/state.py
Fix some docstrings for correct description, typos, typing information, consistency, etc.
For typing information, the docstring was updated to what is in code, but we could instead fix the code where it makes sense: e.g. when the docstring expects a the name of the Archiver (a str) but an Archiver is passed instead, we could actually pass the name. I'm willing to fix it either way.
=> Fix some docstrings

src/wily/commands/graph.py
When fixing #190, I missed a place where `path` should become `path_` and that leads to wrong line labels in graph. This PR fixes the issue introduced in #191.
=> Fix graph not displaying filenames as line labels

pyproject.toml, src/wily/commands/report.py, test/integration/test_report.py
When running `wily report --changes`, it's possible to end up with no data to show, which results in an `IndexError` from tabulate. In this PR the same [guard-clause](https://blog.boot.dev/clean-code/guard-clauses/#guard-clauses) strategy of #197 is used to avoid that, while logging an error explaining why no output is generated.
This fixes an error that surfaced in #201, but I can't see why it would be triggered by that change.
=> Avoid report erroring out if there is no data to show

src/wily/__main__.py, src/wily/commands/diff.py, src/wily/commands/index.py, src/wily/commands/list_metrics.py, src/wily/commands/rank.py, src/wily/commands/report.py, src/wily/helper/__init__.py, test/integration/test_diff.py, test/integration/test_index.py, test/integration/test_list_metrics.py, test/integration/test_rank.py, test/integration/test_report.py, test/unit/test_helper.py
Adds `--wrap` to commands, so output that is too wide for a given terminal width is wrapped inside the table cells. 
Uses `shutil.get_terminal_size()` to get terminal size, then calculates an approximation of maximum column width and passes that as [`maxcolwidths` and `maxheadercolwidths` parameters to tabulate.tabulate(](https://github.com/astanin/python-tabulate#automating-multilines)).
Adds some tests, but not exact output testing.
Fixes #81, except for very narrow terminals with lots of metrics.
=> Allow output from commands to be wrapped to terminal width (fix #81)

src/wily/helper/__init__.py, test/unit/test_helper.py
If `sys.stdout` is a `StringIO` instance, `sys.stdout.encoding` will be `None` and `wily.helper.get_style()` will error out due to trying to call `.lower()` on it. This PR adds a check to handle that case.
Found while updating #199, due to a test that mocked stdout in this way.
=> Handle sys.stdout.encoding being None in get_style()

src/wily/commands/diff.py
Newer versions of ruff started flagging an error in `src/wily/commands/diff.py`. This PR is the result of merely calling ruff with the `--fix` option:
```
src\wily\commands\diff.py:143:25: UP032 [*] Use f-string instead of `format` call
141 |                   if current > new:  # type: ignore
142 |                       metrics_data.append(
143 |                           "{0:n} -> \u001b[{2}m{1:n}\u001b[0m".format(
|  _________________________^
144 | |                             current, new, BAD_COLORS[metric.measure]
145 | |                         )
| |_________________________^ UP032
146 |                       )
147 |                   elif current < new:  # type: ignore
|
= help: Convert to f-string
src\wily\commands\diff.py:149:25: UP032 [*] Use f-string instead of `format` call …
```
=> Fix ruff error due to use of .format() in diff.py

src/wily/templates/css/main.css
As shown in #186, the table containing metrics in HTML report doesn't scroll horizontally, so we can't see some metrics when displaying too many of them. This trivial PR changes the CSS so that the table has `overflow` set to `scroll` instead of `hidden`.
=> Fix HTML report table not being scrollable (fix #186)

src/wily/commands/list_metrics.py
We currently display `repr` for metric_type and aggregate in list-metrics, e.g. `<class 'float'>` and `<function mean at 0x000002C3B88BDC60>`. This PR changes that to using class and function names instead, e.g. `float` and `mean`.
Before:
```
cyclomatic operator:
╒════════════╤═══════════════════════╤═════════════════╤═══════════════════╤═════════════════════╕
│ Name       │ Description           │ Type            │ Measure           │ Aggregate           │
╞════════════╪═══════════════════════╪═════════════════╪═══════════════════╪═════════════════════╡
│ complexity │ Cyclomatic Complexity │ <class 'float'> │ MetricType.AimLow │ <function mean at   │
│            │                       │                 │                   │ 0x000002C3B88BDC60> │ …
```
=> Use class/function names for metric_type and aggregate in list-metrics

src/wily/commands/graph.py
When #205 landed, we stopped setting `z_axis` to `None`, but still test it against being `None`. This causes the `size`of `marker` to be an empty list instead of zero, hiding graph markers. This tiny PR fixes that.
Before:
After:
=> Restore displaying graph markers

src/wily/__main__.py, src/wily/archivers/git.py, src/wily/cache.py, src/wily/commands/build.py, src/wily/commands/diff.py, src/wily/commands/index.py, src/wily/commands/rank.py, src/wily/commands/report.py, src/wily/config/__init__.py, src/wily/config/types.py, src/wily/helper/__init__.py, src/wily/operators/cyclomatic.py, src/wily/operators/halstead.py, src/wily/operators/maintainability.py, src/wily/operators/raw.py, src/wily/state.py
This PR converts wily's logging from using f-strings to `%` style messages.
Fixes #219.
=> Lazy-format all logging calls (fix #219)

src/wily/archivers/__init__.py, src/wily/archivers/git.py, src/wily/commands/build.py, src/wily/commands/graph.py, src/wily/commands/index.py, src/wily/commands/rank.py, src/wily/commands/report.py, src/wily/config/__init__.py, src/wily/helper/__init__.py, src/wily/operators/__init__.py, src/wily/operators/cyclomatic.py, src/wily/operators/halstead.py, src/wily/operators/maintainability.py, src/wily/operators/raw.py
This PR adds some more typing information, including handling most complaints from mypy.
=> Add some more typing

src/wily/operators/cyclomatic.py, src/wily/operators/halstead.py, test/integration/test_complex_commits.py
As a first step to address #217, allowing wily to generate annotated source listings with inline visualization of code metrics, we need to record line numbers for code blocks when building the cache.
Radon already supplies line numbers (lineno and endline) for Cyclomatic Complexity, so we just record those in the detailed metrics.
For Halstead line numbers, we need to customize visitor, harvester and some other pieces. [PRs](https://github.com/rubik/radon/pull/247) and [issues](https://github.com/rubik/radon/issues/248) upstreaming this work have already started being submitted to radon.
This PR is necessary regardless of whether the `annotate` feature lands as a command or is kept as a separate tool.
=> Add line numbers for metrics in Cyclomatic and Halstead operators
